### ISSUE TITLE
Plugin jobs check does not have correct functionality

### ISSUE THREAD

**Issue by Konsonanz** [frmendes/geometry#253]
`geometry_prompt_jobs_check` function uses the following code do determine if it's running or not:
```
[[ $(print -P '%j') == "0" ]]
```
But this checks the success value and not the stdout of the operation and always succeeds, with numerous jobs and zero running.
If you now load another plugin before jobs there will be a plugin spacer, empty space since jobs is not actually printing anything and another plugin spacer.

**Comment by jedahan** [comment]
Thanks for reporting! I think this is fixed in the mnml branch, would you mind testing http://github.com/geometry-zsh/geometry/tree/mnml ?

**Comment by Konsonanz** [comment]
Thanks for responding! The issue still persists:
![2019-06-02 21-19-20](https://user-images.githubusercontent.com/46794176/58766228-9b98fb80-856b-11e9-81c1-e5b52c03cf82.png)
As you can see, there still is an unwanted space inserted, as well as incositend behaviour if just hitting enter (spacer gone).

**Comment by jedahan** [comment]
So the space is a problem with geometry_exec_time, checking that now.

```zsh
a() { echo a }
b() { echo b }
GEOMETRY_RPROMPT=(a geometry_exec_time b)
```

**Comment by jedahan** [comment]
Okay I think I pushed a fix, can you try now?

**Comment by jedahan** [comment]
I also fixed a bug where different shells could clobber the exec time :)

**Comment by Konsonanz** [comment]
Appreciate the fix for exec_time.
But unfortunately, still a space from geometry_jobs with no jobs running:
![2019-06-02 22-21-55](https://user-images.githubusercontent.com/46794176/58766934-46adb300-8574-11e9-801b-ca660a46d5af.png)

**Comment by jedahan** [comment]
Thanks for being patient, I think I squashed it this time.

**Comment by jedahan** [comment]
![jerbs](https://user-images.githubusercontent.com/32407/58767581-671d4380-855b-11e9-88c3-5e360b7bf314.png)

**Comment by Konsonanz** [comment]
That did it :) Thank you very much!
